@startuml CRE546-564 Cross-cutting concerns
!include <archimate/Archimate>
left to right direction
Motivation_Driver(CRE546564, "=CRE 546-564\nCross-cutting concerns")
Motivation_Goal(CRE760765, "=CRE760-765\nXSS protection")
Motivation_Goal(CRE760764, "=CRE760-764\nInjection protection")
Motivation_Goal(CRE161451, "=CRE161-451\nOutput encoding and injection prevention")
Motivation_Goal(CRE620101, "=CRE620-101\nForce output encoding for specific interpreter's context")
Motivation_Goal(CRE170772, "=CRE170-772\nCryptography")
Motivation_Goal(CRE542270, "=CRE542-270\nSecure random values")
Motivation_Goal(CRE027210, "=CRE027-210\nCreate random GUIDs with cryptographically secure random number generators")
Motivation_Goal(CRE028727, "=CRE028-727\nCSRF protection")
Motivation_Goal(CRE342055, "=CRE342-055\nSet 'samesite' attribute for cookie-based session tokens")
Motivation_Goal(CRE623550, "=CRE623-550\nDenial Of Service protection")
Motivation_Goal(CRE854643, "=CRE854-643\nRobust business logic")
Motivation_Goal(CRE552588, "=CRE552-588\nDetect and prevent unusual activity")
Motivation_Goal(CRE534605, "=CRE534-605\nEnforce natural sequence of business flows to avoid abuse")
Motivation_Goal(CRE601182, "=CRE601-182\nParallel execution robustness")
Motivation_Goal(CRE670660, "=CRE670-660\nDo not share unsynchronized state on high-value logic flows")
Motivation_Goal(CRE064808, "=CRE064-808\nEncode output context-specifically")
Motivation_Goal(CRE366835, "=CRE366-835\nEscape output against XSS")
Motivation_Goal(CRE804220, "=CRE804-220\nSet httponly attribute for cookie-based session tokens")
Motivation_Goal(CRE866553, "=CRE866-553\nMemory, String, and Unmanaged Code")
Motivation_Goal(CRE482771, "=CRE482-771\nCheck boundaries against integer overflow weaknesses")
Motivation_Goal(CRE486813, "=CRE486-813\nConfiguration")
Motivation_Goal(CRE233748, "=CRE233-748\nConfiguration hardening")
Motivation_Goal(CRE180488, "=CRE180-488\nProper Configuration for all applications and frameworks")
Motivation_Goal(CRE062850, "=CRE062-850\nMFA/OTP")
Motivation_Goal(CRE553413, "=CRE553-413\nSupport subscriber-provided authentication devices")
Motivation_Goal(CRE155155, "=CRE155-155\nArchitecture")
Motivation_Goal(CRE326704, "=CRE326-704\nArchitecture/design processes")
Motivation_Goal(CRE124564, "=CRE124-564\nConfiguration Management")
Motivation_Goal(CRE080466, "=CRE080-466\nDeveloper Configuration Management")
Motivation_Goal(CRE223780, "=CRE223-780\nSecret storage")
Motivation_Goal(CRE508702, "=CRE508-702\nUse key vaults")
Motivation_Goal(CRE228551, "=CRE228-551\nTLS")
Motivation_Goal(CRE668364, "=CRE668-364\nLog TLS connection failures")
Motivation_Goal(CRE362550, "=CRE362-550\nPersonal data handling")
Motivation_Goal(CRE447083, "=CRE447-083\nPrivacy-preserving personal data logic")
Motivation_Goal(CRE082327, "=CRE082-327\nInform users clearly about the collection and use of personal data,  and use it only after opt-in consent.")
Motivation_Goal(CRE571640, "=CRE571-640\nPersonal data handling management")
Motivation_Goal(CRE068102, "=CRE068-102\nDescribe high-level system architecture and perform threat modeling on it every critical change and regularly")
Motivation_Goal(CRE010308, "=CRE010-308\nInput validation")
Motivation_Goal(CRE848711, "=CRE848-711\nEnforce input validation on a trusted service layer")
Motivation_Goal(CRE841757, "=CRE841-757\nUse approved cryptographic algorithms in generation, seeding and verification of OTPs")
Motivation_Goal(CRE646227, "=CRE646-227\nLog and reject re-use of valid time-based OTP tokens and notify device holder.")
Motivation_Goal(CRE404126, "=CRE404-126\nUse time-based OTP only once")
Motivation_Goal(CRE543428, "=CRE543-428\nUse security module to store one-time password verification keys")
Motivation_Goal(CRE681823, "=CRE681-823\nDefined lifetime of time-based one-time password")
Motivation_Goal(CRE354752, "=CRE354-752\nDo not offer weak (clear text) multi-factor authenticators by default")
Motivation_Goal(CRE206254, "=CRE206-254\nUse secure random to generate initial authentication codes")
Motivation_Goal(CRE708355, "=CRE708-355\nSecure implemented architecture")
Motivation_Goal(CRE048612, "=CRE048-612\nEncode user input before logging")
Motivation_Goal(CRE636347, "=CRE636-347\nHTTP security headers")
Motivation_Goal(CRE268100, "=CRE268-100\nConfigure Referrer-Policy properly")
Motivation_Goal(CRE783255, "=CRE783-255\nStore cryptographic keys securely")
Motivation_Goal(CRE101217, "=CRE101-217\nUse lookup secrets only once")
Motivation_Goal(CRE418853, "=CRE418-853\nMonitor unusual activities on system")
Motivation_Goal(CRE346640, "=CRE346-640\nGenerate multi-factor lookup secrets with sufficient entropy")
Motivation_Goal(CRE524446, "=CRE524-446\nMandate using multi factor authentication")
Motivation_Goal(CRE664571, "=CRE664-571\nEnsure proper generation of secure random")
Motivation_Goal(CRE440361, "=CRE440-361\nEnsure that physical single factor OTP generator can be revoked fully immediately when lost")
Motivation_Goal(CRE400007, "=CRE400-007\nEncrypt data at rest")
Motivation_Goal(CRE742432, "=CRE742-432\nEncryption algorithms")
Motivation_Goal(CRE433122, "=CRE433-122\nUse nonces and initialization vectors only once")
Motivation_Goal(CRE541441, "=CRE541-441\nValidate HTTP request headers")
Motivation_Goal(CRE316272, "=CRE316-272\nWhitelist CORS resources")
Motivation_Goal(CRE525361, "=CRE525-361\nAuthenticate by OTP token entry or user-initiated action on multi factor device")
Motivation_Goal(CRE483715, "=CRE483-715\nWhite-list HTTP methods")
Motivation_Goal(CRE757271, "=CRE757-271\nUse source code control system with change traceability and access control")
Motivation_Goal(CRE384344, "=CRE384-344\nStore and serve user-uploaded files such that they cannot execute/damage server or client")
Motivation_Goal(CRE878880, "=CRE878-880\nPerform cryptographic operations in constant time")
Motivation_Goal(CRE036147, "=CRE036-147\nConfigure HSTS configuration properly")
Motivation_Goal(CRE380540, "=CRE380-540\nEnsure business flows' thread safety/resistance to race conditions")
Motivation_Goal(CRE278413, "=CRE278-413\nMutually authenticate application components. Minimize privileges")
Motivation_Goal(CRE078427, "=CRE078-427\nSet the highest feasible work factor for bcrypt")
Motivation_Goal(CRE636854, "=CRE636-854\nEncrypt all communications")
Motivation_Goal(CRE515021, "=CRE515-021\nSandbox, containerize and/or isolate applications at the network level")
Motivation_Goal(CRE441132, "=CRE441-132\nUse weak crypto only for backwards compatibility")
Motivation_Goal(CRE356282, "=CRE356-282\nMinimize sensitive data scattering and retention")
Motivation_Goal(CRE132146, "=CRE132-146\nApply defense-in-depth techniques/processes for protection, detection, and timely response to network-based attacks.")
Motivation_Goal(CRE072713, "=CRE072-713\nManage standard technologies and frameworks")
Motivation_Goal(CRE630573, "=CRE630-573\nDetect and protect against automation abuse")
Motivation_Goal(CRE774888, "=CRE774-888\nDo not store secrets in the code")
Motivation_Goal(CRE764765, "=CRE764-765\nSanitization and sandboxing")
Motivation_Goal(CRE881434, "=CRE881-434\nSanitize user input before passing content to mail systems (SMTP/IMAP injection)")
Motivation_Goal(CRE622203, "=CRE622-203\nStore passwords salted and hashed")
Motivation_Goal(CRE622835, "=CRE622-835\nGenerate initial passwords with sufficient secure random, short expiration time and do not allow to reuse the initial password.")
Motivation_Goal(CRE831570, "=CRE831-570\nUse memory-safe functions exclusively")
Motivation_Goal(CRE727043, "=CRE727-043\nEnsure secure algorithms for generating session tokens")
Motivation_Goal(CRE704530, "=CRE704-530\nEnforce high entropy session tokens")
Motivation_Goal(CRE816631, "=CRE816-631\nEnsure timely expiration of out of band authentication request, code, or tokens")
Motivation_Goal(CRE168186, "=CRE168-186\nUse out of band authentication requests, codes or tokens only once")
Motivation_Goal(CRE102811, "=CRE102-811\nCommunicate out of band multi factor authentication requests, codes or tokens independently and securely")
Motivation_Goal(CRE342764, "=CRE342-764\nOnly store hashed authentication codes")
Motivation_Goal(CRE881321, "=CRE881-321\nStore credentials securely")
Motivation_Goal(CRE821832, "=CRE821-832\nEnsure keys and passwords are replaceable")
Motivation_Goal(CRE065388, "=CRE065-388\nConfigure X-Content-Type-Options properly")
Motivation_Goal(CRE435702, "=CRE435-702\nCommunication encryption")
Motivation_Goal(CRE527034, "=CRE527-034\nProtect communication between application components")
Motivation_Goal(CRE058527, "=CRE058-527\nSecure name/address resolution service")
Motivation_Goal(CRE513845, "=CRE513-845\nUse unpredictable multi-factor lookup secrets")
Motivation_Goal(CRE333858, "=CRE333-858\nResist stolen credentials")
Motivation_Goal(CRE430636, "=CRE430-636\nVerify TLS certificates and trust chain")
Motivation_Goal(CRE336512, "=CRE336-512\nEnsure integrity of DNS entries and domains")
Motivation_Goal(CRE542488, "=CRE542-488\nUse cryptographically secure random number generators")
Motivation_Goal(CRE308515, "=CRE308-515\nPrevent security disclosure")
Motivation_Goal(CRE208805, "=CRE208-805\nDisable debug mode in production")
Motivation_Goal(CRE824732, "=CRE824-732\nForce format strings as constants")
Motivation_Goal(CRE036725, "=CRE036-725\nSet content HTTP response type")
Motivation_Goal(CRE820878, "=CRE820-878\nDocument all trust boundaries and significant data flows")
Motivation_Goal(CRE743237, "=CRE743-237\nValidatie/enforce HTTP inputs (against HTTP parameter pollution attacks)")
Motivation_Goal(CRE456535, "=CRE456-535\nMonitor for realistic 'human time' business logic flows")
Motivation_Goal(CRE745045, "=CRE745-045\nDo not fall back to insecure protocols in TCP")
Motivation_Goal(CRE031447, "=CRE031-447\nWhitelist all external (HTTP) input")
Motivation_Goal(CRE547283, "=CRE547-283\nProtect against LFI / RFI")
Motivation_Goal(CRE145310, "=CRE145-310\nSanitize, disable, or sandbox untrusted SVG scriptable content")
Motivation_Goal(CRE032213, "=CRE032-213\nUse an isolated security module for cryptographic operations")
Motivation_Goal(CRE076470, "=CRE076-470\nBiometric authenticators only as secondary factors")
Motivation_Goal(CRE814322, "=CRE814-322\nWhitelist data sources and sinks")
Motivation_Goal(CRE725682, "=CRE725-682\nEnable configurable alert against usage anomalies")
Motivation_Goal(CRE585408, "=CRE585-408\nChallenge nonce cryptography")
Motivation_Goal(CRE002801, "=CRE002-801\nUse approved cryptographic algorithms for generation, seeding and verification")
Motivation_Goal(CRE344611, "=CRE344-611\nUse centralized reusable security controls")
Motivation_Goal(CRE646462, "=CRE646-462\nSanitize, disable, or sandbox untrusted scriptable or template language content")
Motivation_Goal(CRE660867, "=CRE660-867\nImplement business logic limits against identified business risks")
Motivation_Goal(CRE743110, "=CRE743-110\nDo not disclose technical information in HTTP header or response")
Motivation_Goal(CRE422005, "=CRE422-005\nSanitize/sandbox user input where template-injection is a threat")
Motivation_Goal(CRE287251, "=CRE287-251\nUse a unique challenge nonce of sufficient size")
Motivation_Goal(CRE806367, "=CRE806-367\nEncode output near the consuming interpreter")
Motivation_Goal(CRE612252, "=CRE612-252\nSeparate GraphQL (or similar) authorization logic from data layer")
Motivation_Goal(CRE268088, "=CRE268-088\nLimit query impact GraphQL/data layer expression DoS")
Motivation_Goal(CRE134412, "=CRE134-412\nProtect sensitive functionalities against race conditions")
Motivation_Goal(CRE762451, "=CRE762-451\nEnsure users can remove or export their data")
Motivation_Goal(CRE275483, "=CRE275-483\nSecurely store regulated data")
Motivation_Goal(CRE267468, "=CRE267-468\nEncrypt financial data at rest")
Motivation_Goal(CRE605735, "=CRE605-735\nAuthenticate all external connections")
Motivation_Goal(CRE267031, "=CRE267-031\nProtect the availability of resources by providing more to higher-priority processes")
Motivation_Goal(CRE786224, "=CRE786-224\nAuthenticate encrypted data")
Motivation_Goal(CRE405411, "=CRE405-411\nAvoid using of Origin header for authentication of access control")
Motivation_Goal(CRE640364, "=CRE640-364\nEnforce access control on trusted parts/serverside")
Motivation_Goal(CRE764507, "=CRE764-507\nRestrict XML parsing (against XXE)")
Motivation_Goal(CRE224321, "=CRE224-321\nEncrypt health data at rest")
Motivation_Goal(CRE154031, "=CRE154-031\nHarden application by excluding unwanted functionality")
Motivation_Goal(CRE650560, "=CRE650-560\nEnforce access control on trusted service layer")
Motivation_Goal(CRE248646, "=CRE248-646\nDisable insecure SSL/TLS versions")
Motivation_Goal(CRE122287, "=CRE122-287\nEnsure cryptographic elements can be upgraded or replaced")
Motivation_Goal(CRE186540, "=CRE186-540\nDo not expose data through HTTP verb")
Motivation_Goal(CRE134207, "=CRE134-207\nProtect against XML/XPath injection")
Motivation_Goal(CRE317743, "=CRE317-743\nDo not use eval or dynamic code execution functions")
Motivation_Goal(CRE462245, "=CRE462-245\nRemove unnecessary elements from external components (e.g. features, documentation, configuration)")
Motivation_Goal(CRE482866, "=CRE482-866\nEncrypt personal data at rest")
Motivation_Goal(CRE736237, "=CRE736-237\nSet metadata/content-Disposition for API responses")
Motivation_Goal(CRE042550, "=CRE042-550\nProtect against mass parameter assignment attack")
Motivation_Goal(CRE176154, "=CRE176-154\nMonitor expectation of usage intensity (e.g. number of requests)")
Motivation_Goal(CRE674425, "=CRE674-425\nUse state of the art cryptographic configuration")
Motivation_Goal(CRE653242, "=CRE653-242\nEnforce schema on type/contents of structured data")
Motivation_Goal(CRE232325, "=CRE232-325\nTreat client-secrets as insecure")
Motivation_Goal(CRE060472, "=CRE060-472\nUse CSRF protection against authenticated functionality, add anti-automation controls for unauthenticated functionality")
Motivation_Goal(CRE742431, "=CRE742-431\nUse approved cryptographic algorithms")
Motivation_Goal(CRE257668, "=CRE257-668\nConfigure CSP configuration properly")
Motivation_Goal(CRE660052, "=CRE660-052\nValidate max input/file sizes")
Motivation_Goal(CRE117371, "=CRE117-371\nUse a centralized access control mechanism")
Motivation_Goal(CRE607671, "=CRE607-671\nProtect against JS or JSON injection attacks")
Motivation_Goal(CRE333888, "=CRE333-888\nDo not expose data through API URLs")
Motivation_Goal(CRE232217, "=CRE232-217\nWhitelist redirected/forwarded URLs")
Motivation_Goal(CRE732873, "=CRE732-873\nLock/precompile queries (parameterization) to avoid injection attacks")
Motivation_Goal(CRE426842, "=CRE426-842\nVerify the authenticity of both headers and payload")
Motivation_Goal(CRE767701, "=CRE767-701\nVerify strong TLS algorithms by testing")
Motivation_Goal(CRE857718, "=CRE857-718\nProtect against OS command injection attack")
Motivation_Goal(CRE163518, "=CRE163-518\nCheck uploaded archives for decompression attacks (eg zip bombs)")
Motivation_Goal(CRE480071, "=CRE480-071\nPrevent Click jacking through X-Frame-Options or CSP")
Motivation_Goal(CRE533516, "=CRE533-516\nEncode output while preserving user input formatting")
Motivation_Goal(CRE146706, "=CRE146-706\nEnforce JSON schema before processing")
Motivation_Goal(CRE082530, "=CRE082-530\nUse unique random salt with sufficient entropy for each credential")
Motivation_Goal(CRE077781, "=CRE077-781\nUse separately stored secret salt (pepper)")
Motivation_Goal(CRE036810, "=CRE036-810\nLet cryptographic modules fail securely")
Motivation_Goal(CRE538446, "=CRE538-446\nSanitize unstructured data")
Motivation_Goal(CRE504340, "=CRE504-340\nEncrypt sensitive data with algorithms that provide both confidentiality and integrity")
Motivation_Goal(CRE615744, "=CRE615-744\nProtect against directory browsing/discovery attacks")
Motivation_Goal(CRE767435, "=CRE767-435\nSet the highest feasible iteration count for PBKDF2")
Motivation_Goal(CRE463820, "=CRE463-820\nLimit size and number of uploaded files")
Motivation_Goal(CRE113133, "=CRE113-133\nUse centralized authentication mechanism")
Motivation_Goal(CRE464084, "=CRE464-084\nAdd CSRF protection for cookie based REST services")
Motivation_Goal(CRE542445, "=CRE542-445\nSanitize untrusted HTML input")
Motivation_Goal(CRE531558, "=CRE531-558\nProtect against LDAP injection")
Motivation_Goal(CRE657084, "=CRE657-084\n(SSRF) When depending on internal server input, use validation sanitization and whitelisting")
Motivation_Goal(CRE340375, "=CRE340-375\nUse a dedicated secrets management solution")
Motivation_Goal(CRE820421, "=CRE820-421\nAuthenticate HTTP headers added by a trusted proxy or SSO device")
Motivation_Requirement(STD4080811839429554639, "=ASVS V5.3.1\nVerify that output encoding is relevant for the interpreter and context required. For example, use encoders specifically for HTML values, HTML attributes, JavaScript, URL parameters, HTTP headers, SMTP, and others as the context requires, especially from untrusted inputs (e.g. names with Unicode or apostrophes, such as „Å≠„Åì or O'Hara).")
Motivation_Requirement(STD9051588863077783593, "=ASVS V6.3.2\nVerify that random GUIDs are created using the GUID v4 algorithm, and a Cryptographically-secure Pseudo-random Number Generator (CSPRNG). GUIDs created using other pseudo-random number generators may be predictable.")
Motivation_Principle(STD6469004446255946100, "=NIST 800-63\nare g")
Motivation_Requirement(STD7651559068572918361, "=ASVS V11.1.1\nVerify that the application will only process business logic flows for the same user in sequential step order and without skipping steps.")
Motivation_Requirement(STD3946844854271859312, "=ASVS V1.11.2\nVerify that all high-value business logic flows, including authentication, session management and access control, do not share unsynchronized state.")
Motivation_Requirement(STD6629353030201991898, "=ASVS V5.3.5\nVerify that where parameterized or safer mechanisms are not present, context-specific output encoding is used to protect against injection attacks, such as the use of SQL escaping to protect against SQL injection.")
Motivation_Requirement(STD7825391631360540643, "=ASVS V5.3.3\nVerify that context-aware, preferably automated - or at worst, manual - output escaping protects against reflected, stored, and DOM based XSS.")
Motivation_Principle(STD474274928516734148, "=NIST 800-63\n7.1.1")
Motivation_Requirement(STD2866165028154948298, "=ASVS V5.4.3\nVerify that sign, range, and input validation techniques are used to prevent integer overflows.")
Motivation_Requirement(STD7550345713720179793, "=ASVS V14.1.3\nVerify that server configuration is hardened as per the recommendations of the application server and frameworks in use.")
Motivation_Constraint(STD2768539752143655909, "=OWASP Top 10 2021 A05\nSecurity Misconfiguration")
Motivation_Requirement(STD4027524514958729209, "=ASVS V2.3.2\nVerify that enrollment and use of user-provided authentication devices are supported, such as a U2F or FIDO tokens.")
Motivation_Principle(STD2107454921108160965, "=NIST 800-53 v5\nSA-20 Customized Development of Critical Components")
Motivation_Principle(STD3740380286179403175, "=ISO 27001 8.4\nAccess to source code")
Motivation_Requirement(STD3874059256196476493, "=ASVS V1.6.2\nVerify that consumers of cryptographic services protect key material and other secrets by using key vaults or API based alternatives.")
Motivation_Principle(STD4497190176775384145, "=NIST 800-53 v5\nCM-5 Access Restrictions for Change")
Motivation_Principle(STD6131681216614805009, "=NIST 800-53 v5\nSC-28 PROTECTION OF INFORMATION AT REST")
Motivation_Requirement(STD8085007139079526332, "=ASVS V8.3.3\nVerify that users are provided clear language regarding collection and use of supplied personal information and that users have provided opt-in consent for the use of that data before it is used in any way.")
Motivation_Principle(STD8748019573544079330, "=NIST 800-53 v5\nPT-4 Consent")
Motivation_Principle(STD5444365898211244137, "=NIST 800-53 v5\nSC-31 Covert Channel Analysis")
Motivation_Principle(STD1818515817231324529, "=NIST 800-53 v5\nSI-19 De-identification")
Motivation_Requirement(STD4322586569586045560, "=ASVS V1.5.3\nVerify that input validation is enforced on a trusted service layer. ([C5](https://owasp.org/www-project-proactive-controls/#div-numbering))")
Motivation_Principle(STD1171805167470504593, "=NIST 800-63\n5.1.5.2")
Motivation_Requirement(STD1229670439043025275, "=ASVS V2.7.1\nVerify that clear text out of band (NIST 'restricted') authenticators, such as SMS or PSTN, are not offered by default, and stronger alternatives such as push notifications are offered first.")
Motivation_Requirement(STD3625894193802873099, "=ASVS V2.7.6\nVerify that the initial authentication code is generated by a secure random number generator, containing at least 20 bits of entropy (typically a six digital random number is sufficient).")
Motivation_Principle(STD2522106026901729890, "=NIST 800-53 v5\nSC-44 Detonation Chambers")
Motivation_Requirement(STD3273379829011140872, "=ASVS V7.3.1\nVerify that all logging components appropriately encode data to prevent log injection.")
Motivation_Requirement(STD7366248179888445424, "=ASVS V14.4.6\nVerify that a suitable Referrer-Policy header is included to avoid exposing sensitive information in the URL through the Referer header to untrusted parties.")
Motivation_Requirement(STD7103041944692201501, "=ASVS V2.9.1\nVerify that cryptographic keys used in verification are stored securely and protected against disclosure, such as using a Trusted Platform Module (TPM) or Hardware Security Module (HSM), or an OS service that can use this secure storage.")
Motivation_Requirement(STD8777965198900607206, "=ASVS V2.6.1\nVerify that lookup secrets can be used only once.")
Motivation_Requirement(STD4872078829118986124, "=ASVS V11.1.7\nVerify that the application monitors for unusual events or activity from a business logic perspective. For example, attempts to perform actions out of order or actions which a normal user would never attempt.")
Motivation_Requirement(STD2117760444061976519, "=ASVS V2.6.2\nVerify that lookup secrets have sufficient randomness (112 bits of entropy), or if less than 112 bits of entropy, salted with a unique and random 32-bit salt and hashed with an approved one-way hash.")
Motivation_Constraint(STD1048725173147207521, "=OWASP Top 10 2021 A03\nInjection")
Motivation_Requirement(STD326833705031769410, "=ASVS V3.4.2\nVerify that cookie-based session tokens have the 'HttpOnly' attribute set.")
Motivation_Principle(STD2155751308298362187, "=NIST 800-53 v5\nPM-25 Minimization of Personally Identifiable Information Used in Testing, Training, and Research")
Motivation_Requirement(STD5816978269427426677, "=ASVS V2.8.4\nVerify that time-based OTP can be used only once within the validity period.")
Motivation_Principle(STD1615899861487802496, "=NIST 800-63\n5.2.8")
Motivation_Requirement(STD297601816326472383, "=ASVS V6.3.3\nVerify that random numbers are created with proper entropy even when the application is under heavy load, or that the application degrades gracefully in such circumstances.")
Motivation_Requirement(STD2268027461634520567, "=ASVS V3.4.3\nVerify that cookie-based session tokens utilize the 'SameSite' attribute to limit exposure to cross-site request forgery attacks.")
Motivation_Principle(STD6413577409303734207, "=NIST 800-53 v5\nSI-22 Information Diversity")
Motivation_Principle(STD603508942396023735, "=NIST 800-63\n5.2.1")
Motivation_Requirement(STD5783922976879043376, "=NIST SSDF PS.1.1\nStore all forms of code – including source")
Motivation_Requirement(STD3398485325163711239, "=ASVS V6.2.6\nVerify that nonces, initialization vectors, and other single use numbers must not be used more than once with a given encryption key. The method of generation must be appropriate for the algorithm being used.")
Motivation_Requirement(STD4511116953731105716, "=ASVS V14.5.3\nVerify that the Cross-Origin Resource Sharing (CORS) Access-Control-Allow-Origin header uses a strict allow list of trusted domains and subdomains to match against and does not support the 'null' origin.")
Motivation_Principle(STD5064405894478197388, "=NIST 800-63\n5.2.9")
Motivation_Requirement(STD3950677465759713948, "=ASVS V14.5.1\nVerify that the application server only accepts the HTTP methods in use by the application/API, including pre-flight OPTIONS, and logs/alerts on any requests that are not valid for the application context.")
Motivation_Assessment(STD5463903408699631625, "=SAMM D-SA-A\nArchitecture Design")
Motivation_Requirement(STD5243208643990086395, "=ASVS V1.10.1\nVerify that a source code control system is in use, with procedures to ensure that check-ins are accompanied by issues or change tickets. The source code control system should have access control and identifiable users to allow traceability of any changes.")
Motivation_Requirement(STD6947691064766244782, "=ASVS V1.12.2\nVerify that user-uploaded files - if required to be displayed or downloaded from the application - are served by either octet stream downloads, or from an unrelated domain, such as a cloud file storage bucket. Implement a suitable Content Security Policy (CSP) to reduce the risk from XSS vectors or other attacks from the uploaded file.")
Motivation_Requirement(STD3868675253800599144, "=ASVS V6.2.8\nVerify that all cryptographic operations are constant-time, with no 'short-circuit' operations in comparisons, calculations, or returns, to avoid leaking information.")
Motivation_Requirement(STD9002595645551840047, "=ASVS V14.4.5\nVerify that a Strict-Transport-Security header is included on all responses and for all subdomains, such as Strict-Transport-Security: max-age=15724800; includeSubdomains.")
Motivation_Requirement(STD2805516095809743664, "=ASVS V1.11.3\nVerify that all high-value business logic flows, including authentication, session management and access control are thread safe and resistant to time-of-check and time-of-use race conditions.")
Motivation_Requirement(STD6942204151887781179, "=ASVS V1.2.2\nVerify that communications between application components, including APIs, middleware and data layers, are authenticated. Components should have the least necessary privileges needed.")
Motivation_Requirement(STD2126855198569500288, "=ASVS V2.4.4\nVerify that if bcrypt is used, the work factor SHOULD be as large as verification server performance will allow, with a minimum of 10.")
Motivation_Requirement(STD7642284214144005380, "=ASVS V9.2.2\nVerify that encrypted communications such as TLS is used for all inbound and outbound connections, including for management ports, monitoring, authentication, API, or web service calls, database, cloud, serverless, mainframe, external, and partner connections. The server must not fall back to insecure or unencrypted protocols.")
Motivation_Principle(STD1729474030500113065, "=NIST 800-53 v5\nCM-3 Configuration Change Control")
Motivation_Constraint(STD3058518917586496527, "=OWASP Top 10 2021 A04\nInsecure Design")
Motivation_Requirement(STD713027386504769841, "=ASVS V1.14.5\nVerify that application deployments adequately sandbox, containerize and/or isolate at the network level to delay and deter attackers from attacking other applications, especially when they are performing sensitive or dangerous actions such as deserialization.")
Motivation_Requirement(STD5919318297867804387, "=ASVS V6.2.5\nVerify that known insecure block modes (i.e. ECB, etc.), padding modes (i.e. PKCS#1 v1.5, etc.), ciphers with small block sizes (i.e. Triple-DES, Blowfish, etc.), and weak hashing algorithms (i.e. MD5, SHA1, etc.) are not used unless required for backwards compatibility.")
Motivation_Principle(STD2143641925771448319, "=NIST 800-53 v5\nSI-21 Information Refresh")
Motivation_Principle(STD5712315583517003546, "=NIST 800-53 v5\nSI-18 Personally Identifiable Information Quality Operations")
Motivation_Principle(STD2813712128846054715, "=Cloud Controls Matrix IVS-09\nNetwork Defense")
Motivation_Assessment(STD9115352070640613456, "=SAMM D-SA-B\nTechnology Management")
Motivation_Requirement(STD200477071909494043, "=ASVS V11.1.4\nVerify that the application has anti-automation controls to protect against excessive calls such as mass data exfiltration, business logic requests, file uploads or denial of service attacks.")
Motivation_Requirement(STD6102498053737308660, "=ASVS V2.10.4\nVerify passwords, integrations with databases and third-party systems, seeds and internal secrets, and API keys are managed securely and not included in the source code or stored within source code repositories. Such storage SHOULD resist offline attacks. The use of a secure software key store (L1), hardware TPM, or an HSM (L3) is recommended for password storage.")
Motivation_Requirement(STD26077417166890817, "=ASVS V5.2.3\nVerify that the application sanitizes user input before passing to mail systems to protect against SMTP or IMAP injection.")
Motivation_Requirement(STD3867839241501442604, "=NIST SSDF PW.9.2\nImplement the default settings (or groups of default settings, if applicable), and document each setting for software administrators.")
Motivation_Requirement(STD1271425091684599691, "=ASVS V2.4.1\nVerify that passwords are stored in a form that is resistant to offline attacks. Passwords SHALL be salted and hashed using an approved one-way key derivation or password hashing function. Key derivation and password hashing functions take a password, a salt, and a cost factor as inputs when generating a password hash.")
Motivation_Principle(STD9000472990139917714, "=NIST 800-63\nA.3")
Motivation_Requirement(STD8974246562461456267, "=ASVS V5.4.1\nVerify that the application uses memory-safe string, safer memory copy and pointer arithmetic to detect or prevent stack, buffer, or heap overflows.")
Motivation_Principle(STD8136033107036447578, "=NIST 800-63\n7.1")
Motivation_Requirement(STD9056678305565366714, "=NIST SSDF PW.9.1\nDefine a secure baseline by determining how to configure each setting that has an effect on security or a security-related setting so that the default settings are secure and do not weaken the security functions provided by the platform, network infrastructure, or services.")
Motivation_Principle(STD5901894808219119249, "=ISO 27001 8.24\nUse of cryptography")
Motivation_Principle(STD7993220575731007442, "=NIST 800-53 v5\nPT-3 Personally Identifiable Information Processing Purposes")
Motivation_Requirement(STD7512989856810839238, "=ASVS V2.8.3\nVerify that approved cryptographic algorithms are used in the generation, seeding, and verification of OTPs.")
Motivation_Principle(STD6657933460088656983, "=NIST 800-53 v5\nPM-18 Privacy Program Plan")
Motivation_Principle(STD248608147278092264, "=NIST 800-63\n5.1.3.2")
Motivation_Principle(STD8318573248862031403, "=NIST 800-63\n5.1.1.1")
Motivation_Requirement(STD8933904433122238000, "=ASVS V1.6.3\nVerify that all keys and passwords are replaceable and are part of a well-defined process to re-encrypt sensitive data.")
Motivation_Requirement(STD8936334329591819474, "=ASVS V14.4.4\nVerify that all responses contain a X-Content-Type-Options: nosniff header.")
Motivation_Requirement(STD3478456578034634986, "=ASVS V1.9.1\nVerify the application encrypts communications between components, particularly when these components are in different containers, systems, sites, or cloud providers.")
Motivation_Principle(STD1434531569007872414, "=NIST 800-53 v5\nSC-21 Secure Name/address Resolution Service (recursive or Caching Resolver)")
Motivation_Principle(STD2384038130287347909, "=NIST 800-63\n5.1.2.2")
Motivation_Principle(STD7287841038319836200, "=NIST 800-63\n5.2.5")
Motivation_Requirement(STD6101088217553477368, "=ASVS V9.2.1\nVerify that connections to and from the server use trusted TLS certificates. Where internally generated or self-signed certificates are used, the server must be configured to only trust specific internal CAs and specific self-signed certificates. All others should be rejected.")
Motivation_Requirement(STD1464412973015293875, "=ASVS V2.7.5\nVerify that the out of band verifier retains only a hashed version of the authentication code.")
Motivation_Principle(STD6639748503575291324, "=ISO 27001 8.20\nNetworks security")
Motivation_Principle(STD5189545237072093373, "=NIST 800-53 v5\nCM-2 BASELINE CONFIGURATION")
Motivation_Principle(STD4395410280595519172, "=NIST 800-53 v5\nSI-16 Memory Protection")
Motivation_Requirement(STD1707907221975692978, "=ASVS V1.1.5\nVerify definition and security analysis of the application's high-level architecture and all connected remote services.")
Motivation_Requirement(STD7192536726667548469, "=ASVS V6.3.1\nVerify that all random numbers, random file names, random GUIDs, and random strings are generated using the cryptographic module's approved cryptographically secure random number generator when these random values are intended to be not guessable by an attacker.")
Motivation_Principle(STD3830649280846212489, "=NIST 800-53 v5\nPM-24 Data Integrity Board")
Motivation_Requirement(STD1234886326794137231, "=ASVS V14.3.2\nVerify that web or application server and application framework debug modes are disabled in production to eliminate debug features, developer consoles, and unintended security disclosures.")
Motivation_Principle(STD6900918804406646393, "=Cloud Controls Matrix CEK\nCryptography, Encryption & Key Management")
Motivation_Requirement(STD6726530616602405477, "=ASVS V5.4.2\nVerify that format strings do not take potentially hostile input, and are constant.")
Motivation_Requirement(STD57694308868541999, "=ASVS V14.4.1\nVerify that every HTTP response contains a Content-Type header. Also specify a safe character set (e.g., UTF-8, ISO-8859-1) if the content types are text/*, /+xml and application/xml. Content must match with the provided Content-Type header.")
Motivation_Requirement(STD1292718785107915619, "=ASVS V2.2.7\nVerify intent to authenticate by requiring the entry of an OTP token or user-initiated action such as a button press on a FIDO hardware key.")
Motivation_Requirement(STD4751489267849057208, "=ASVS V1.1.4\nVerify documentation and justification of all the application's trust boundaries, components, and significant data flows.")
Motivation_Requirement(STD8631999135293798189, "=ASVS V5.1.1\nVerify that the application has defenses against HTTP parameter pollution attacks, particularly if the application framework makes no distinction about the source of request parameters (GET, POST, cookies, headers, or environment variables).")
Motivation_Requirement(STD5346274330826185755, "=ASVS V11.1.2\nVerify that the application will only process business logic flows with all steps being processed in realistic human time, i.e. transactions are not submitted too quickly.")
Motivation_Requirement(STD2695946646389788646, "=ASVS V9.1.1\nVerify that TLS is used for all client connectivity, and does not fall back to insecure or unencrypted communications.")
Motivation_Requirement(STD1701905797526439765, "=ASVS V5.1.3\nVerify that all input (HTML form fields, REST requests, URL parameters, HTTP headers, cookies, batch files, RSS feeds, etc) is validated using positive validation (allow lists).")
Motivation_Requirement(STD8947715344810976943, "=ASVS V5.3.9\nVerify that the application protects against Local File Inclusion (LFI) or Remote File Inclusion (RFI) attacks.")
Motivation_Principle(STD5313655920200084695, "=NIST 800-53 v5\nCM-7 Least Functionality")
Motivation_Assessment(STD3547472890412074370, "=SAMM D-TA-B\nThreat modeling")
Motivation_Requirement(STD6143025347538367091, "=ASVS V5.2.7\nVerify that the application sanitizes, disables, or sandboxes user-supplied Scalable Vector Graphics (SVG) scriptable content, especially as they relate to XSS resulting from inline scripts, and foreignObject.")
Motivation_Requirement(STD8638174404474186601, "=ASVS V6.4.2\nVerify that key material is not exposed to the application but instead uses an isolated security module like a vault for cryptographic operations.")
Motivation_Requirement(STD5308302796388067706, "=ASVS V2.8.7\nVerify that biometric authenticators are limited to use only as secondary factors in conjunction with either something you have and something you know.")
Motivation_Principle(STD4331244279706303588, "=NIST 800-53 v5\nCM-11 User-installed Software")
Motivation_Requirement(STD413043216884229840, "=ASVS V12.6.1\nVerify that the web or application server is configured with an allow list of resources or systems to which the server can send requests or load data/files from.")
Motivation_Requirement(STD7301578734738636885, "=ASVS V11.1.8\nVerify that the application has configurable alerting when automated attacks or unusual activity is detected.")
Motivation_Principle(STD87944959051472886, "=ISO 27001 5.34\nPrivacy and protection of personal identifiable information (PII)")
Motivation_Requirement(STD8804853111459636812, "=ASVS V2.9.3\nVerify that approved cryptographic algorithms are used in the generation, seeding, and verification.")
Motivation_Principle(STD8966031350880056401, "=NIST 800-53 v5\nSA-10 Developer Configuration Management")
Motivation_Principle(STD5732439305830981274, "=NIST 800-53 v5\nCM-9 Configuration Management Plan")
Motivation_Requirement(STD170604891416369331, "=ASVS V1.1.6\nVerify implementation of centralized, simple (economy of design), vetted, secure, and reusable security controls to avoid duplicate, missing, ineffective, or insecure controls.")
Motivation_Requirement(STD4236527748095697440, "=ASVS V5.2.8\nVerify that the application sanitizes, disables, or sandboxes user-supplied scriptable or expression template language content, such as Markdown, CSS or XSL stylesheets, BBCode, or similar.")
Motivation_Principle(STD5692427477167245698, "=NIST 800-53 v5\nPT-1 Policy and Procedures")
Motivation_Principle(STD8551955861063716142, "=NIST 800-53 v5\nPT-7 Specific Categories of Personally Identifiable Information")
Motivation_Requirement(STD1100106006064507520, "=ASVS V2.8.1\nVerify that time-based OTPs have a defined lifetime before expiring.")
Motivation_Requirement(STD6012485048870768286, "=ASVS V11.1.5\nVerify the application has business logic limits or validation to protect against likely business risks or threats, identified using threat modeling or similar methodologies.")
Motivation_Requirement(STD2656672072756860999, "=ASVS V14.3.3\nVerify that the HTTP headers or any part of the HTTP response do not expose detailed version information of system components.")
Motivation_Requirement(STD2924105793159486020, "=ASVS V5.2.5\nVerify that the application protects against template injection attacks by ensuring that any user input being included is sanitized or sandboxed.")
Motivation_Requirement(STD7485779680154730149, "=ASVS V2.9.2\nVerify that the challenge nonce is at least 64 bits in length, and statistically unique or unique over the lifetime of the cryptographic device.")
Motivation_Principle(STD1795074412013112313, "=NIST 800-63\n5.1.7.2")
Motivation_Requirement(STD2490436376204891493, "=ASVS V1.5.4\nVerify that output encoding occurs close to or by the interpreter for which it is intended.")
Motivation_Requirement(STD4996481068358163821, "=ASVS V13.4.2\nVerify that GraphQL or other data layer authorization logic should be implemented at the business logic layer instead of the GraphQL layer.")
Motivation_Requirement(STD4920249634499163330, "=ASVS V13.4.1\nVerify that a query allow list or a combination of depth limiting and amount limiting is used to prevent GraphQL or data layer expression Denial of Service (DoS) as a result of expensive, nested queries. For more advanced scenarios, query cost analysis should be used.")
Motivation_Principle(STD2445638612980796695, "=NIST 800-53 v5\nPM-22 Personally Identifiable Information Quality Management")
Motivation_Requirement(STD6182607180809950817, "=ASVS V11.1.6\nVerify that the application does not suffer from 'Time Of Check to Time Of Use' (TOCTOU) issues or other race conditions for sensitive operations.")
Motivation_Requirement(STD140675310574407653, "=ASVS V8.3.2\nVerify that users have a method to remove or export their data on demand.")
Motivation_Requirement(STD8336011349632423274, "=ASVS V6.1.3\nVerify that regulated financial data is stored encrypted while at rest, such as financial accounts, defaults or credit history, tax records, pay history, beneficiaries, or de-anonymized market or research records.")
Motivation_Principle(STD7286685707056408641, "=NIST 800-53 v5\nPM-27 Privacy Reporting")
Motivation_Requirement(STD2358935052751541831, "=ASVS V9.2.5\nVerify that backend TLS connection failures are logged.")
Motivation_Requirement(STD4881928228950357971, "=ASVS V9.2.3\nVerify that all encrypted connections to external systems that involve sensitive information or functions are authenticated.")
Motivation_Principle(STD9014511056260459009, "=NIST 800-53 v5\nSC-6 Resource Availability")
Motivation_Principle(STD7954694618006348030, "=NIST 800-53 v5\nCM-12 Information Location")
Motivation_Assessment(STD1437480348215957195, "=SAMM O-EM-A\nConfiguration Hardening")
Motivation_Principle(STD8786605627247064007, "=NIST 800-53 v5\nSC-20 Secure Name/address Resolution Service (authoritative Source)")
Motivation_Principle(STD6906765682320108799, "=NIST 800-53 v5\nSC-29 Heterogeneity")
Motivation_Principle(STD3622292409645179946, "=NIST 800-53 v5\nCM-1 Policy and Procedures")
Motivation_Requirement(STD908466741105990260, "=ASVS V6.2.7\nVerify that encrypted data is authenticated via signatures, authenticated cipher modes, or HMAC to ensure that ciphertext is not altered by an unauthorized party.")
Motivation_Principle(STD479525827924477118, "=NIST 800-53 v5\nSC-39 Process Isolation")
Motivation_Assessment(STD5133153541015874921, "=SAMM I-SD-B\nSecret Management")
Motivation_Requirement(STD2211190817577300267, "=ASVS V14.5.2\nVerify that the supplied Origin header is not used for authentication or access control decisions, as the Origin header can easily be changed by an attacker.")
Motivation_Requirement(STD3276289354384575579, "=ASVS V1.4.1\nVerify that trusted enforcement points, such as access control gateways, servers, and serverless functions, enforce access controls. Never enforce access controls on the client.")
Motivation_Requirement(STD2854608144958249826, "=ASVS V5.5.2\nVerify that the application correctly restricts XML parsers to only use the most restrictive configuration possible and to ensure that unsafe features such as resolving external entities are disabled to prevent XML eXternal Entity (XXE) attacks.")
Motivation_Requirement(STD8001176005226384439, "=ASVS V6.1.2\nVerify that regulated health data is stored encrypted while at rest, such as medical records, medical device details, or de-anonymized research records.")
Motivation_Principle(STD3923691563511957391, "=NIST 800-53 v5\nCM-8 System Component Inventory")
Motivation_Requirement(STD97282320330195934, "=ASVS V10.2.6\nVerify that the application source code and third party libraries do not contain Easter eggs or any other potentially unwanted functionality.")
Motivation_Principle(STD2924880215371495721, "=ISO 27001 8.22\nSegregation of networks")
Motivation_Requirement(STD2008488601005481070, "=ASVS V4.1.1\nVerify that the application enforces access control rules on a trusted service layer, especially if client-side access control is present and could be bypassed.")
Motivation_Requirement(STD4263697682867080043, "=ASVS V9.1.3\nVerify that only the latest recommended versions of the TLS protocol are enabled, such as TLS 1.2 and TLS 1.3. The latest version of the TLS protocol should be the preferred option.")
Motivation_Requirement(STD5381996079694711410, "=ASVS V6.2.4\nVerify that random number, encryption or hashing algorithms, key lengths, rounds, ciphers or modes, can be reconfigured, upgraded, or swapped at any time, to protect against cryptographic breaks. ([C8](https://owasp.org/www-project-proactive-controls/#div-numbering))")
Motivation_Requirement(STD1980930028294462865, "=ASVS V8.3.1\nVerify that sensitive data is sent to the server in the HTTP message body or headers, and that query string parameters from any HTTP verb do not contain sensitive data.")
Motivation_Requirement(STD9165854079424683204, "=ASVS V5.3.10\nVerify that the application protects against XPath injection or XML injection attacks.")
Motivation_Requirement(STD3685153800908998976, "=ASVS V5.2.4\nVerify that the application avoids the use of eval() or other dynamic code execution features. Where there is no alternative, any user input being included must be sanitized or sandboxed before being executed.")
Motivation_Principle(STD120281157784981940, "=Cheat_sheets\nSecrets Management Cheat Sheet")
Motivation_Requirement(STD1746456677934472546, "=ASVS V2.6.3\nVerify that lookup secrets are resistant to offline attacks, such as predictable values.")
Motivation_Requirement(STD2966171527164446985, "=ASVS V14.2.2\nVerify that all unneeded features, documentation, sample applications and configurations are removed.")
Motivation_Requirement(STD1638285717357723113, "=ASVS V6.1.1\nVerify that regulated private data is stored encrypted while at rest, such as Personally Identifiable Information (PII), sensitive personal information, or data assessed likely to be subject to EU's GDPR.")
Motivation_Principle(STD765540160273972351, "=NIST 800-53 v5\nPM-20 Dissemination of Privacy Program Information")
Motivation_Requirement(STD7838124120120041801, "=ASVS V14.4.2\nVerify that all API responses contain a Content-Disposition: attachment; filename='api.json' header (or other appropriate filename for the content type).")
Motivation_Requirement(STD4700914619595406404, "=ASVS V5.1.2\nVerify that frameworks protect against mass parameter assignment attacks, or that the application has countermeasures to protect against unsafe parameter assignment, such as marking fields private or similar.")
Motivation_Requirement(STD4452557742075196703, "=ASVS V8.1.4\nVerify the application can detect and alert on abnormal numbers of requests, such as by IP, user, total per hour or day, or whatever makes sense for the application.")
Motivation_Principle(STD1617579865808647513, "=NIST 800-53 v5\nSC-27 Platform-independent Applications")
Motivation_Requirement(STD4769007708799982174, "=ASVS V6.2.3\nVerify that encryption initialization vector, cipher configuration, and block modes are configured securely using the latest advice.")
Motivation_Principle(STD2073339972120571381, "=NIST 800-53 v5\nCM-14 Signed Components")
Motivation_Requirement(STD8812422875198006735, "=ASVS V5.1.4\nVerify that structured data is strongly typed and validated against a defined schema including allowed characters, length and pattern (e.g. credit card numbers, e-mail addresses, telephone numbers, or validating that two related fields are reasonable, such as checking that suburb and zip/postcode match).")
Motivation_Requirement(STD1686726702542109054, "=ASVS V1.6.4\nVerify that the architecture treats client-side secrets--such as symmetric keys, passwords, or API tokens--as insecure and never uses them to protect or access sensitive data.")
Motivation_Requirement(STD6383688792844198891, "=ASVS V4.2.2\nVerify that the application or framework enforces a strong anti-CSRF mechanism to protect authenticated functionality, and effective anti-automation or anti-CSRF protects unauthenticated functionality.")
Motivation_Principle(STD6086986525712519186, "=NIST 800-53 v5\nSC-5 DENIAL-OF-SERVICE PROTECTION")
Motivation_Requirement(STD5358536969561966470, "=NIST SSDF PW.1.1\nUse forms of risk modeling – such as threat modeling, attack modeling, or attack surface mapping – to help assess the security risk for the software.")
Motivation_Principle(STD514670105548114252, "=NIST 800-53 v5\nCM-13 Data Action Mapping")
Motivation_Principle(STD3623141177719946455, "=NIST 800-63\n6.1.3")
Motivation_Requirement(STD5098964627968424592, "=ASVS V6.2.2\nVerify that industry proven or government approved cryptographic algorithms, modes, and libraries are used, instead of custom coded cryptography.")
Motivation_Principle(STD2027613183302397145, "=NIST 800-53 v5\nPT-6 System of Records Notice")
Motivation_Principle(STD705805859980333984, "=ISO 27001 8.27\nSecure system architecture and engineering principles")
Motivation_Principle(STD5434798488613985993, "=ISO 27001 8.9\nConfiguration management")
Motivation_Requirement(STD7627260682213681033, "=ASVS V2.8.5\nVerify that if a time-based multi-factor OTP token is re-used during the validity period, it is logged and rejected with secure notifications being sent to the holder of the device.")
Motivation_Principle(STD3244381602209187154, "=NIST 800-53 v5\nCM-6 Configuration Settings")
Motivation_Requirement(STD7548097754692454329, "=ASVS V14.4.3\nVerify that a Content Security Policy (CSP) response header is in place that helps mitigate impact for XSS attacks like HTML, DOM, JSON, and JavaScript injection vulnerabilities.")
Motivation_Requirement(STD602550366812280187, "=ASVS V2.10.3\nVerify that passwords are stored with sufficient protection to prevent offline recovery attacks, including local system access.")
Motivation_Requirement(STD6376579766365465203, "=ASVS V2.2.6\nVerify replay resistance through the mandated use of One-time Passwords (OTP) devices, cryptographic authenticators, or lookup codes.")
Motivation_Requirement(STD6094101582391357765, "=ASVS V12.1.1\nVerify that the application will not accept large files that could fill up storage or cause a denial of service.")
Motivation_Principle(STD2370854207656141286, "=NIST 800-53 v5\nPT-2 Authority to Process Personally Identifiable Information")
Motivation_Principle(STD5706156428591980178, "=NIST 800-53 v5\nSC-12 CRYPTOGRAPHIC KEY ESTABLISHMENT AND MANAGEMENT")
Motivation_Requirement(STD1193624288181141354, "=ASVS V1.4.4\nVerify the application uses a single and well-vetted access control mechanism for accessing protected data and resources. All requests must pass through this single mechanism to avoid copy and paste or insecure alternative paths.")
Motivation_Requirement(STD7263433430453812132, "=ASVS V10.3.3\nVerify that the application has protection from subdomain takeovers if the application relies upon DNS entries or DNS subdomains, such as expired domain names, out of date DNS pointers or CNAMEs, expired projects at public source code repos, or transient cloud APIs, serverless functions, or storage buckets (*autogen-bucket-id*.cloud.example.com) or similar. Protections can include ensuring that DNS names used by applications are regularly checked for expiry or change.")
Motivation_Principle(STD85823483535291012, "=NIST 800-53 v5\nCM-4 Impact Analyses")
Motivation_Requirement(STD4603323552391466306, "=ASVS V2.7.4\nVerify that the out of band authenticator and verifier communicates over a secure independent channel.")
Motivation_Principle(STD6655445797794627029, "=NIST 800-53 v5\nSI-14 Non-persistence")
Motivation_Principle(STD3170841783494255773, "=NIST 800-53 v5\nSC-13 Cryptographic Protection")
Motivation_Requirement(STD1760607344259346200, "=ASVS V5.3.6\nVerify that the application protects against JSON injection attacks, JSON eval attacks, and JavaScript expression evaluation.")
Motivation_Principle(STD7419763886018749203, "=NIST 800-63\n5.2.3")
Motivation_Principle(STD5898356918574307736, "=NIST 800-53 v5\nPM-21 Accounting of Disclosures")
Motivation_Requirement(STD5557582992893811277, "=ASVS V2.7.2\nVerify that the out of band verifier expires out of band authentication requests, codes, or tokens after 10 minutes.")
Motivation_Requirement(STD274114662748851380, "=ASVS V13.1.3\nVerify API URLs do not expose sensitive information, such as the API key, session tokens etc.")
Motivation_Principle(STD2096131898512727657, "=NIST 800-53 v5\nSI-15 Information Output Filtering")
Motivation_Principle(STD6708602143393212397, "=Cloud Controls Matrix DSP\nData Security and Privacy Lifecycle Management")
Motivation_Principle(STD8263336799016017600, "=ISO 27001 8.11\nData masking")
Motivation_Requirement(STD1562990429100961875, "=ASVS V2.2.4\nVerify impersonation resistance against phishing, such as the use of multi-factor authentication, cryptographic devices with intent (such as connected keys with a push to authenticate), or at higher AAL levels, client-side certificates.")
Motivation_Requirement(STD4944517124676361900, "=ASVS V5.1.5\nVerify that URL redirects and forwards only allow destinations which appear on an allow list, or show a warning when redirecting to potentially untrusted content.")
Motivation_Principle(STD6973169161545405478, "=NIST 800-53 v5\nSC-17 Public Key Infrastructure Certificates")
Motivation_Requirement(STD10669490054099009, "=ASVS V5.3.4\nVerify that data selection or database queries (e.g. SQL, HQL, ORM, NoSQL) use parameterized queries, ORMs, entity frameworks, or are otherwise protected from database injection attacks.")
Motivation_Principle(STD7999355854963567047, "=NIST 800-53 v5\nSC-3 Security Function Isolation")
Motivation_Requirement(STD341178691181919999, "=ASVS V2.8.2\nVerify that symmetric keys used to verify submitted OTPs are highly protected, such as by using a hardware security module or secure operating system based key storage.")
Motivation_Requirement(STD7094337701969878440, "=ASVS V13.2.6\nVerify that the message headers and payload are trustworthy and not modified in transit. Requiring strong encryption for transport (TLS only) may be sufficient in many cases as it provides both confidentiality and integrity protection. Per-message digital signatures can provide additional assurance on top of the transport protections for high-security applications but bring with them additional complexity and risks to weigh against the benefits.")
Motivation_Requirement(STD4747201327441876998, "=ASVS V9.1.2\nVerify using up to date TLS testing tools that only strong cipher suites are enabled, with the strongest cipher suites set as preferred.")
Motivation_Requirement(STD868728904290719612, "=ASVS V5.3.8\nVerify that the application protects against OS command injection and that operating system calls use parameterized OS queries or use contextual command line output encoding.")
Motivation_Requirement(STD6748692934059170143, "=ASVS V12.1.2\nVerify that the application checks compressed files (e.g. zip, gz, docx, odt) against maximum allowed uncompressed size and against maximum number of files before uncompressing the file.")
Motivation_Principle(STD7674724703647072462, "=Cloud Controls Matrix IVS-06\nSegmentation and Segregation")
Motivation_Requirement(STD7239688518083919246, "=ASVS V3.2.2\nVerify that session tokens possess at least 64 bits of entropy.")
Motivation_Requirement(STD6643383094447982774, "=ASVS V14.4.7\nVerify that the content of a web application cannot be embedded in a third-party site by default and that embedding of the exact resources is only allowed where necessary by using suitable Content-Security-Policy: frame-ancestors and X-Frame-Options response headers.")
Motivation_Requirement(STD2753301933509317493, "=ASVS V5.3.2\nVerify that output encoding preserves the user's chosen character set and locale, such that any Unicode character point is valid and safely handled.")
Motivation_Principle(STD539510405156317636, "=NIST 800-53 v5\nCM-10 Software Usage Restrictions")
Motivation_Principle(STD2386357490154046020, "=NIST 800-53 v5\nPM-19 Privacy Program Leadership Role")
Motivation_Constraint(STD6758996751528730024, "=OWASP Top 10 2021 A02\nCryptographic Failures")
Motivation_Requirement(STD2754581810215339715, "=ASVS V3.2.4\nVerify that session tokens are generated using approved cryptographic algorithms.")
Motivation_Requirement(STD1392629772430707721, "=ASVS V13.2.2\nVerify that JSON schema validation is in place and verified before accepting input.")
Motivation_Requirement(STD5509510967143937357, "=ASVS V2.4.2\nVerify that the salt is at least 32 bits in length and be chosen arbitrarily to minimize salt value collisions among stored hashes. For each credential, a unique salt value and the resulting hash SHALL be stored.")
Motivation_Principle(STD1280241731542268450, "=NIST 800-53 v5\nSI-23 Information Fragmentation")
Motivation_Principle(STD3682339230982086952, "=NIST 800-53 v5\nSA-23 Specialization")
Motivation_Requirement(STD2532137343219138888, "=ASVS V2.4.5\nVerify that an additional iteration of a key derivation function is performed, using a salt value that is secret and known only to the verifier. Generate the salt value using an approved random bit generator [SP 800-90Ar1] and provide at least the minimum security strength specified in the latest revision of SP 800-131A. The secret salt value SHALL be stored separately from the hashed passwords (e.g., in a specialized device like a hardware security module).")
Motivation_Principle(STD7076318402558874132, "=NIST 800-53 v5\nPT-5 Privacy Notice")
Motivation_Requirement(STD5809244266104834024, "=ASVS V6.2.1\nVerify that all cryptographic modules fail securely, and errors are handled in a way that does not enable Padding Oracle attacks.")
Motivation_Requirement(STD2978902532188258226, "=ASVS V2.7.3\nVerify that the out of band verifier authentication requests, codes, or tokens are only usable once, and only for the original authentication request.")
Motivation_Requirement(STD3970829682940051687, "=ASVS V5.2.2\nVerify that unstructured data is sanitized to enforce safety measures such as allowed characters and length.")
Motivation_Requirement(STD8971993605155554456, "=ASVS V8.3.7\nVerify that sensitive or private information that is required to be encrypted, is encrypted using approved algorithms that provide both confidentiality and integrity.")
Motivation_Principle(STD694619954142336029, "=NIST 800-63\n5.1.4.2")
Motivation_Requirement(STD9071798015477695268, "=ASVS V4.3.2\nVerify that directory browsing is disabled unless deliberately desired. Additionally, applications should not allow discovery or disclosure of file or directory metadata, such as Thumbs.db, .DS_Store, .git or .svn folders.")
Motivation_Principle(STD8157000111370185576, "=NIST 800-63\n5.1.1.2")
Motivation_Requirement(STD5958511180839201102, "=NIST SSDF PW.1.3\nWhere appropriate, build in support for using standardized security features and services (e.g., enabling software to integrate with existing log management, identity management, access control, and vulnerability management systems) instead of creating proprietary implementations of security features and services.")
Motivation_Requirement(STD1221055465435430339, "=ASVS V12.1.3\nVerify that a file size quota and maximum number of files per user is enforced to ensure that a single user cannot fill up the storage with too many files, or excessively large files.")
Motivation_Principle(STD5921394541217517616, "=ISO 27001 8.12\nData leakage prevention")
Motivation_Principle(STD724106910810859229, "=NIST 800-53 v5\nSC-32 System Partitioning")
Motivation_Principle(STD8212171988406192023, "=OWASP Secure Headers Project\nconfiguration")
Motivation_Principle(STD3293055429165776372, "=NIST 800-53 v5\nSA-17 Developer Security and Privacy Architecture and Design")
Motivation_Requirement(STD1171123965239038055, "=ASVS V2.4.3\nVerify that if PBKDF2 is used, the iteration count SHOULD be as large as verification server performance will allow, typically at least 100,000 iterations.")
Motivation_Requirement(STD233846824378937777, "=ASVS V1.2.3\nVerify that the application uses a single vetted authentication mechanism that is known to be secure, can be extended to include strong authentication, and has sufficient logging and monitoring to detect account abuse or breaches.")
Motivation_Requirement(STD3428293838083505331, "=ASVS V13.2.3\nVerify that RESTful web services that utilize cookies are protected from Cross-Site Request Forgery via the use of at least one or more of the following: double submit cookie pattern, CSRF nonces, or Origin request header checks.")
Motivation_Requirement(STD3351677148698109320, "=ASVS V5.2.1\nVerify that all untrusted HTML input from WYSIWYG editors or similar is properly sanitized with an HTML sanitizer library or framework feature. ([C5](https://owasp.org/www-project-proactive-controls/#div-numbering))")
Motivation_Principle(STD7391134076867187343, "=NIST 800-53 v5\nPT-8 Computer Matching Requirements")
Motivation_Requirement(STD458934823834369873, "=ASVS V5.3.7\nVerify that the application protects against LDAP injection vulnerabilities, or that specific security controls to prevent LDAP injection have been implemented.")
Motivation_Requirement(STD7270418348873648023, "=ASVS V5.2.6\nVerify that the application protects against SSRF attacks, by validating or sanitizing untrusted data or HTTP file metadata, such as filenames and URL input fields, and uses allow lists of protocols, domains, paths and ports.")
Motivation_Requirement(STD5776153258530424495, "=ASVS V2.8.6\nVerify physical single-factor OTP generator can be revoked in case of theft or other loss. Ensure that revocation is immediately effective across logged in sessions, regardless of location.")
Motivation_Principle(STD1330747404477513456, "=NIST 800-53 v5\nPL-8 SECURITY AND PRIVACY ARCHITECTURES")
Motivation_Requirement(STD1947136785651619825, "=ASVS V6.4.1\nVerify that a secrets management solution such as a key vault is used to securely create, store, control access to and destroy secrets.")
Motivation_Requirement(STD6667295343078166306, "=ASVS V2.3.1\nVerify system generated initial passwords or activation codes SHOULD be securely randomly generated, SHOULD be at least 6 characters long, and MAY contain letters and numbers, and expire after a short period of time. These initial secrets must not be permitted to become the long term password.")
Motivation_Principle(STD6937817391933577501, "=Cloud Controls Matrix IVS-05\nProduction and Non-Production Environments")
Motivation_Requirement(STD4762516916974558392, "=ASVS V14.5.4\nVerify that HTTP headers added by a trusted proxy or SSO devices, such as a bearer token, are authenticated by the application.")
Rel_Specialization(CRE275483, CRE224321)
Rel_Realization(CRE804220, STD474274928516734148)
Rel_Specialization(CRE585408, CRE287251)
Rel_Realization(CRE646227, STD1171805167470504593)
Rel_Realization(CRE527034, STD3478456578034634986)
Rel_Realization(CRE513845, STD1746456677934472546)
Rel_Specialization(CRE764765, CRE145310)
Rel_Realization(CRE486813, STD2768539752143655909)
Rel_Realization(CRE233748, STD1437480348215957195)
Rel_Specialization(CRE062850, CRE525361)
Rel_Realization(CRE831570, STD8974246562461456267)
Rel_Realization(CRE508702, STD3874059256196476493)
Rel_Realization(CRE080466, STD5783922976879043376)
Rel_Specialization(CRE161451, CRE547283)
Rel_Specialization(CRE062850, CRE354752)
Rel_Realization(CRE064808, STD6629353030201991898)
Rel_Realization(CRE841757, STD1171805167470504593)
Rel_Realization(CRE342055, STD6469004446255946100)
Rel_Realization(CRE482771, STD2866165028154948298)
Rel_Realization(CRE622835, STD9000472990139917714)
Rel_Realization(CRE745045, STD2695946646389788646)
Rel_Association(CRE623550, CRE660052)
Rel_Specialization(CRE742432, CRE674425)
Rel_Realization(CRE036725, STD57694308868541999)
Rel_Specialization(CRE435702, CRE527034)
Rel_Realization(CRE268088, STD4920249634499163330)
Rel_Specialization(CRE541441, CRE483715)
Rel_Specialization(CRE435702, CRE426842)
Rel_Realization(CRE543428, STD694619954142336029)
Rel_Realization(CRE433122, STD3398485325163711239)
Rel_Association(CRE155155, CRE113133)
Rel_Realization(CRE804220, STD326833705031769410)
Rel_Association(CRE623550, CRE267031)
Rel_Specialization(CRE223780, CRE508702)
Rel_Association(CRE155155, CRE708355)
Rel_Realization(CRE161451, STD2096131898512727657)
Rel_Association(CRE362550, CRE482866)
Rel_Specialization(CRE275483, CRE482866)
Rel_Specialization(CRE546564, CRE486813)
Rel_Specialization(CRE010308, CRE232217)
Rel_Realization(CRE124564, STD514670105548114252)
Rel_Realization(CRE042550, STD4700914619595406404)
Rel_Realization(CRE170772, STD6758996751528730024)
Rel_Specialization(CRE326704, CRE072713)
Rel_Association(CRE623550, CRE463820)
Rel_Realization(CRE180488, STD7550345713720179793)
Rel_Realization(CRE154031, STD97282320330195934)
Rel_Realization(CRE326704, STD705805859980333984)
Rel_Realization(CRE513845, STD2384038130287347909)
Rel_Specialization(CRE542270, CRE542488)
Rel_Realization(CRE354752, STD248608147278092264)
Rel_Realization(CRE060472, STD6383688792844198891)
Rel_Association(CRE170772, CRE400007)
Rel_Realization(CRE783255, STD7103041944692201501)
Rel_Realization(CRE145310, STD6143025347538367091)
Rel_Realization(CRE380540, STD2805516095809743664)
Rel_Realization(CRE180488, STD9056678305565366714)
Rel_Specialization(CRE742432, CRE878880)
Rel_Specialization(CRE764765, CRE422005)
Rel_Specialization(CRE010308, CRE653242)
Rel_Association(CRE362550, CRE571640)
Rel_Realization(CRE065388, STD8936334329591819474)
Rel_Realization(CRE333858, STD7287841038319836200)
Rel_Realization(CRE571640, STD1818515817231324529)
Rel_Specialization(CRE161451, CRE134207)
Rel_Realization(CRE180488, STD3867839241501442604)
Rel_Specialization(CRE223780, CRE622203)
Rel_Association(CRE170772, CRE742432)
Rel_Specialization(CRE636347, CRE480071)
Rel_Association(CRE170772, CRE435702)
Rel_Realization(CRE543428, STD1171805167470504593)
Rel_Specialization(CRE552588, CRE660867)
Rel_Association(CRE170772, CRE704530)
Rel_Specialization(CRE636347, CRE036147)
Rel_Realization(CRE072713, STD9115352070640613456)
Rel_Specialization(CRE223780, CRE774888)
Rel_Realization(CRE854643, STD5921394541217517616)
Rel_Association(CRE170772, CRE223780)
Rel_Specialization(CRE223780, CRE821832)
Rel_Realization(CRE426842, STD7094337701969878440)
Rel_Realization(CRE646462, STD4236527748095697440)
Rel_Realization(CRE124564, STD5434798488613985993)
Rel_Realization(CRE783255, STD1795074412013112313)
Rel_Specialization(CRE010308, CRE042550)
Rel_Realization(CRE674425, STD4769007708799982174)
Rel_Realization(CRE077781, STD2532137343219138888)
Rel_Realization(CRE727043, STD2754581810215339715)
Rel_Realization(CRE571640, STD7286685707056408641)
Rel_Specialization(CRE308515, CRE208805)
Rel_Association(CRE155155, CRE344611)
Rel_Association(CRE623550, CRE854643)
Rel_Specialization(CRE124564, CRE080466)
Rel_Realization(CRE504340, STD8971993605155554456)
Rel_Association(CRE170772, CRE206254)
Rel_Realization(CRE342764, STD1464412973015293875)
Rel_Realization(CRE881434, STD26077417166890817)
Rel_Specialization(CRE161451, CRE064808)
Rel_Association(CRE760764, CRE866553)
Rel_Realization(CRE404126, STD5816978269427426677)
Rel_Specialization(CRE161451, CRE806367)
Rel_Association(CRE486813, CRE154031)
Rel_Specialization(CRE546564, CRE155155)
Rel_Specialization(CRE601182, CRE380540)
Rel_Realization(CRE464084, STD3428293838083505331)
Rel_Realization(CRE404126, STD1171805167470504593)
Rel_Realization(CRE525361, STD5064405894478197388)
Rel_Realization(CRE571640, STD2155751308298362187)
Rel_Realization(CRE076470, STD7419763886018749203)
Rel_Specialization(CRE552588, CRE534605)
Rel_Specialization(CRE161451, CRE533516)
Rel_Association(CRE170772, CRE841757)
Rel_Realization(CRE708355, STD6655445797794627029)
Rel_Realization(CRE068102, STD5358536969561966470)
Rel_Realization(CRE607671, STD1760607344259346200)
Rel_Specialization(CRE062850, CRE076470)
Rel_Specialization(CRE400007, CRE504340)
Rel_Specialization(CRE447083, CRE762451)
Rel_Realization(CRE814322, STD413043216884229840)
Rel_Association(CRE623550, CRE630573)
Rel_Realization(CRE124564, STD85823483535291012)
Rel_Realization(CRE031447, STD1701905797526439765)
Rel_Realization(CRE515021, STD713027386504769841)
Rel_Specialization(CRE546564, CRE623550)
Rel_Specialization(CRE062850, CRE102811)
Rel_Realization(CRE623550, STD6086986525712519186)
Rel_Realization(CRE336512, STD7263433430453812132)
Rel_Realization(CRE268100, STD7366248179888445424)
Rel_Realization(CRE486813, STD3244381602209187154)
Rel_Specialization(CRE400007, CRE742432)
Rel_Specialization(CRE223780, CRE077781)
Rel_Realization(CRE287251, STD1795074412013112313)
Rel_Specialization(CRE546564, CRE058527)
Rel_Specialization(CRE742432, CRE122287)
Rel_Realization(CRE124564, STD539510405156317636)
Rel_Realization(CRE342055, STD2268027461634520567)
Rel_Association(CRE760765, CRE804220)
Rel_Association(CRE486813, CRE764507)
Rel_Specialization(CRE742432, CRE441132)
Rel_Specialization(CRE062850, CRE681823)
Rel_Specialization(CRE062850, CRE168186)
Rel_Specialization(CRE062850, CRE553413)
Rel_Specialization(CRE552588, CRE456535)
Rel_Specialization(CRE228551, CRE636854)
Rel_Specialization(CRE223780, CRE082530)
Rel_Realization(CRE620101, STD4080811839429554639)
Rel_Realization(CRE482866, STD1638285717357723113)
Rel_Realization(CRE354752, STD1229670439043025275)
Rel_Realization(CRE841757, STD694619954142336029)
Rel_Specialization(CRE636347, CRE065388)
Rel_Specialization(CRE161451, CRE857718)
Rel_Realization(CRE068102, STD5444365898211244137)
Rel_Association(CRE760765, CRE257668)
Rel_Realization(CRE346640, STD2384038130287347909)
Rel_Realization(CRE542488, STD7192536726667548469)
Rel_Realization(CRE168186, STD248608147278092264)
Rel_Realization(CRE342764, STD248608147278092264)
Rel_Specialization(CRE223780, CRE340375)
Rel_Realization(CRE102811, STD4603323552391466306)
Rel_Realization(CRE078427, STD8157000111370185576)
Rel_Realization(CRE124564, STD4331244279706303588)
Rel_Realization(CRE660867, STD6012485048870768286)
Rel_Realization(CRE317743, STD3685153800908998976)
Rel_Specialization(CRE742432, CRE433122)
Rel_Realization(CRE622203, STD1271425091684599691)
Rel_Realization(CRE542445, STD3351677148698109320)
Rel_Specialization(CRE854643, CRE552588)
Rel_Specialization(CRE854643, CRE601182)
Rel_Realization(CRE082327, STD8085007139079526332)
Rel_Specialization(CRE326704, CRE068102)
Rel_Specialization(CRE233748, CRE636347)
Rel_Realization(CRE571640, STD6657933460088656983)
Rel_Realization(CRE002801, STD8804853111459636812)
Rel_Association(CRE760764, CRE161451)
Rel_Realization(CRE132146, STD2813712128846054715)
Rel_Realization(CRE571640, STD5692427477167245698)
Rel_Realization(CRE553413, STD4027524514958729209)
Rel_Association(CRE155155, CRE848711)
Rel_Realization(CRE571640, STD2386357490154046020)
Rel_Realization(CRE080466, STD8966031350880056401)
Rel_Specialization(CRE742432, CRE742431)
Rel_Realization(CRE806367, STD2490436376204891493)
Rel_Realization(CRE462245, STD2966171527164446985)
Rel_Realization(CRE538446, STD3970829682940051687)
Rel_Realization(CRE816631, STD248608147278092264)
Rel_Specialization(CRE546564, CRE760765)
Rel_Realization(CRE124564, STD7954694618006348030)
Rel_Realization(CRE531558, STD458934823834369873)
Rel_Realization(CRE486813, STD5189545237072093373)
Rel_Realization(CRE764507, STD2854608144958249826)
Rel_Association(CRE623550, CRE132146)
Rel_Association(CRE170772, CRE664571)
Rel_Realization(CRE824732, STD6726530616602405477)
Rel_Realization(CRE681823, STD694619954142336029)
Rel_Association(CRE760765, CRE384344)
Rel_Specialization(CRE062850, CRE404126)
Rel_Specialization(CRE742432, CRE036810)
Rel_Realization(CRE333888, STD274114662748851380)
Rel_Realization(CRE571640, STD7993220575731007442)
Rel_Realization(CRE760764, STD1048725173147207521)
Rel_Realization(CRE101217, STD2384038130287347909)
Rel_Realization(CRE333858, STD1562990429100961875)
Rel_Realization(CRE732873, STD10669490054099009)
Rel_Realization(CRE615744, STD9071798015477695268)
Rel_Specialization(CRE062850, CRE346640)
Rel_Realization(CRE170772, STD3170841783494255773)
Rel_Specialization(CRE010308, CRE146706)
Rel_Realization(CRE117371, STD1193624288181141354)
Rel_Specialization(CRE062850, CRE816631)
Rel_Realization(CRE848711, STD4322586569586045560)
Rel_Realization(CRE657084, STD7270418348873648023)
Rel_Association(CRE170772, CRE542270)
Rel_Realization(CRE483715, STD3950677465759713948)
Rel_Realization(CRE708355, STD7999355854963567047)
Rel_Realization(CRE767435, STD1171123965239038055)
Rel_Specialization(CRE062850, CRE440361)
Rel_Specialization(CRE552588, CRE725682)
Rel_Realization(CRE340375, STD1947136785651619825)
Rel_Realization(CRE841757, STD7512989856810839238)
Rel_Specialization(CRE764765, CRE657084)
Rel_Realization(CRE326704, STD2107454921108160965)
Rel_Realization(CRE248646, STD4263697682867080043)
Rel_Association(CRE028727, CRE060472)
Rel_Realization(CRE708355, STD1280241731542268450)
Rel_Realization(CRE384344, STD6947691064766244782)
Rel_Realization(CRE422005, STD2924105793159486020)
Rel_Association(CRE623550, CRE725682)
Rel_Realization(CRE163518, STD6748692934059170143)
Rel_Association(CRE486813, CRE186540)
Rel_Realization(CRE622203, STD8157000111370185576)
Rel_Specialization(CRE546564, CRE028727)
Rel_Realization(CRE653242, STD8812422875198006735)
Rel_Association(CRE623550, CRE268088)
Rel_Specialization(CRE010308, CRE031447)
Rel_Specialization(CRE080466, CRE757271)
Rel_Specialization(CRE233748, CRE814322)
Rel_Realization(CRE124564, STD3923691563511957391)
Rel_Realization(CRE082530, STD5509510967143937357)
Rel_Realization(CRE524446, STD1615899861487802496)
Rel_Realization(CRE441132, STD5919318297867804387)
Rel_Realization(CRE326704, STD5463903408699631625)
Rel_Realization(CRE418853, STD4872078829118986124)
Rel_Realization(CRE170772, STD5901894808219119249)
Rel_Realization(CRE571640, STD2027613183302397145)
Rel_Realization(CRE820421, STD4762516916974558392)
Rel_Realization(CRE612252, STD4996481068358163821)
Rel_Association(CRE623550, CRE163518)
Rel_Realization(CRE068102, STD1707907221975692978)
Rel_Realization(CRE134207, STD9165854079424683204)
Rel_Realization(CRE078427, STD2126855198569500288)
Rel_Realization(CRE543428, STD341178691181919999)
Rel_Specialization(CRE228551, CRE745045)
Rel_Realization(CRE168186, STD2978902532188258226)
Rel_Realization(CRE605735, STD4881928228950357971)
Rel_Association(CRE028727, CRE342055)
Rel_Specialization(CRE161451, CRE620101)
Rel_Realization(CRE124564, STD5313655920200084695)
Rel_Specialization(CRE400007, CRE275483)
Rel_Realization(CRE571640, STD6708602143393212397)
Rel_Realization(CRE224321, STD8001176005226384439)
Rel_Realization(CRE660052, STD6094101582391357765)
Rel_Association(CRE170772, CRE248646)
Rel_Realization(CRE267031, STD9014511056260459009)
Rel_Realization(CRE725682, STD7301578734738636885)
Rel_Specialization(CRE742432, CRE786224)
Rel_Realization(CRE525361, STD1292718785107915619)
Rel_Specialization(CRE062850, CRE342764)
Rel_Association(CRE486813, CRE124564)
Rel_Association(CRE155155, CRE650560)
Rel_Specialization(CRE010308, CRE743237)
Rel_Specialization(CRE161451, CRE607671)
Rel_Specialization(CRE223780, CRE078427)
Rel_Realization(CRE786224, STD908466741105990260)
Rel_Realization(CRE102811, STD248608147278092264)
Rel_Specialization(CRE228551, CRE248646)
Rel_Association(CRE155155, CRE612252)
Rel_Realization(CRE122287, STD5381996079694711410)
Rel_Realization(CRE670660, STD3946844854271859312)
Rel_Association(CRE623550, CRE176154)
Rel_Realization(CRE571640, STD5898356918574307736)
Rel_Realization(CRE326704, STD3682339230982086952)
Rel_Realization(CRE206254, STD3625894193802873099)
Rel_Association(CRE760765, CRE764765)
Rel_Realization(CRE767435, STD8157000111370185576)
Rel_Specialization(CRE764765, CRE881434)
Rel_Realization(CRE547283, STD8947715344810976943)
Rel_Realization(CRE186540, STD1980930028294462865)
Rel_Realization(CRE257668, STD7548097754692454329)
Rel_Association(CRE362550, CRE447083)
Rel_Realization(CRE515021, STD7674724703647072462)
Rel_Association(CRE760764, CRE760765)
Rel_Specialization(CRE866553, CRE482771)
Rel_Association(CRE155155, CRE640364)
Rel_Realization(CRE287251, STD7485779680154730149)
Rel_Realization(CRE515021, STD2924880215371495721)
Rel_Association(CRE486813, CRE462245)
Rel_Association(CRE155155, CRE278413)
Rel_Realization(CRE326704, STD6906765682320108799)
Rel_Association(CRE028727, CRE464084)
Rel_Realization(CRE002801, STD1795074412013112313)
Rel_Realization(CRE881321, STD8318573248862031403)
Rel_Association(CRE760765, CRE161451)
Rel_Association(CRE486813, CRE430636)
Rel_Realization(CRE762451, STD140675310574407653)
Rel_Realization(CRE668364, STD2358935052751541831)
Rel_Realization(CRE480071, STD6643383094447982774)
Rel_Realization(CRE134412, STD6182607180809950817)
Rel_Specialization(CRE223780, CRE881321)
Rel_Realization(CRE878880, STD3868675253800599144)
Rel_Specialization(CRE764765, CRE538446)
Rel_Realization(CRE708355, STD2522106026901729890)
Rel_Specialization(CRE228551, CRE430636)
Rel_Realization(CRE456535, STD5346274330826185755)
Rel_Association(CRE170772, CRE527034)
Rel_Realization(CRE068102, STD3547472890412074370)
Rel_Specialization(CRE866553, CRE831570)
Rel_Association(CRE760764, CRE010308)
Rel_Realization(CRE571640, STD8748019573544079330)
Rel_Realization(CRE336512, STD6937817391933577501)
Rel_Realization(CRE774888, STD6102498053737308660)
Rel_Realization(CRE356282, STD2143641925771448319)
Rel_Realization(CRE704530, STD7239688518083919246)
Rel_Association(CRE486813, CRE333888)
Rel_Realization(CRE704530, STD8136033107036447578)
Rel_Specialization(CRE062850, CRE841757)
Rel_Realization(CRE571640, STD2445638612980796695)
Rel_Specialization(CRE601182, CRE670660)
Rel_Realization(CRE821832, STD8933904433122238000)
Rel_Realization(CRE170772, STD5706156428591980178)
Rel_Realization(CRE533516, STD2753301933509317493)
Rel_Realization(CRE326704, STD1617579865808647513)
Rel_Specialization(CRE228551, CRE668364)
Rel_Specialization(CRE546564, CRE170772)
Rel_Realization(CRE571640, STD7391134076867187343)
Rel_Specialization(CRE552588, CRE418853)
Rel_Realization(CRE027210, STD9051588863077783593)
Rel_Specialization(CRE601182, CRE134412)
Rel_Realization(CRE571640, STD3830649280846212489)
Rel_Realization(CRE232325, STD1686726702542109054)
Rel_Realization(CRE743237, STD8631999135293798189)
Rel_Association(CRE170772, CRE543428)
Rel_Specialization(CRE062850, CRE646227)
Rel_Realization(CRE630573, STD200477071909494043)
Rel_Specialization(CRE764765, CRE542445)
Rel_Specialization(CRE636347, CRE268100)
Rel_Realization(CRE113133, STD233846824378937777)
Rel_Realization(CRE820878, STD4751489267849057208)
Rel_Realization(CRE440361, STD5776153258530424495)
Rel_Realization(CRE757271, STD5243208643990086395)
Rel_Specialization(CRE585408, CRE002801)
Rel_Realization(CRE736237, STD7838124120120041801)
Rel_Realization(CRE124564, STD4497190176775384145)
Rel_Specialization(CRE062850, CRE101217)
Rel_Realization(CRE571640, STD7076318402558874132)
Rel_Realization(CRE362550, STD87944959051472886)
Rel_Realization(CRE650560, STD2008488601005481070)
Rel_Realization(CRE036810, STD5809244266104834024)
Rel_Realization(CRE278413, STD6942204151887781179)
Rel_Realization(CRE404126, STD694619954142336029)
Rel_Specialization(CRE866553, CRE824732)
Rel_Association(CRE155155, CRE515021)
Rel_Specialization(CRE062850, CRE513845)
Rel_Realization(CRE857718, STD868728904290719612)
Rel_Realization(CRE176154, STD4452557742075196703)
Rel_Realization(CRE206254, STD248608147278092264)
Rel_Realization(CRE346640, STD2117760444061976519)
Rel_Realization(CRE866553, STD4395410280595519172)
Rel_Realization(CRE622835, STD8157000111370185576)
Rel_Realization(CRE101217, STD8777965198900607206)
Rel_Realization(CRE708355, STD6413577409303734207)
Rel_Association(CRE760765, CRE760764)
Rel_Association(CRE170772, CRE585408)
Rel_Realization(CRE636347, STD8212171988406192023)
Rel_Realization(CRE223780, STD5133153541015874921)
Rel_Realization(CRE124564, STD3622292409645179946)
Rel_Association(CRE623550, CRE456535)
Rel_Realization(CRE124564, STD5732439305830981274)
Rel_Realization(CRE727043, STD8136033107036447578)
Rel_Specialization(CRE541441, CRE820421)
Rel_Realization(CRE082530, STD8157000111370185576)
Rel_Realization(CRE816631, STD5557582992893811277)
Rel_Realization(CRE553413, STD3623141177719946455)
Rel_Specialization(CRE764765, CRE646462)
Rel_Realization(CRE743110, STD2656672072756860999)
Rel_Specialization(CRE223780, CRE767435)
Rel_Realization(CRE344611, STD5958511180839201102)
Rel_Association(CRE170772, CRE228551)
Rel_Specialization(CRE308515, CRE743110)
Rel_Realization(CRE032213, STD8638174404474186601)
Rel_Association(CRE058527, CRE336512)
Rel_Realization(CRE742431, STD5098964627968424592)
Rel_Association(CRE623550, CRE418853)
Rel_Specialization(CRE542270, CRE664571)
Rel_Realization(CRE681823, STD1171805167470504593)
Rel_Realization(CRE571640, STD8551955861063716142)
Rel_Specialization(CRE546564, CRE362550)
Rel_Specialization(CRE764765, CRE317743)
Rel_Realization(CRE636854, STD7642284214144005380)
Rel_Realization(CRE708355, STD479525827924477118)
Rel_Realization(CRE571640, STD765540160273972351)
Rel_Realization(CRE767701, STD4747201327441876998)
Rel_Realization(CRE048612, STD3273379829011140872)
Rel_Realization(CRE708355, STD724106910810859229)
Rel_Realization(CRE316272, STD4511116953731105716)
Rel_Specialization(CRE542270, CRE027210)
Rel_Specialization(CRE400007, CRE232325)
Rel_Realization(CRE463820, STD1221055465435430339)
Rel_Specialization(CRE541441, CRE316272)
Rel_Realization(CRE058527, STD8786605627247064007)
Rel_Association(CRE760765, CRE010308)
Rel_Association(CRE155155, CRE820878)
Rel_Specialization(CRE636347, CRE036725)
Rel_Specialization(CRE764765, CRE268088)
Rel_Association(CRE155155, CRE117371)
Rel_Realization(CRE622835, STD6667295343078166306)
Rel_Realization(CRE336512, STD6639748503575291324)
Rel_Specialization(CRE223780, CRE032213)
Rel_Realization(CRE232217, STD4944517124676361900)
Rel_Association(CRE760764, CRE384344)
Rel_Specialization(CRE541441, CRE405411)
Rel_Realization(CRE170772, STD6973169161545405478)
Rel_Association(CRE760764, CRE764507)
Rel_Specialization(CRE161451, CRE531558)
Rel_Realization(CRE223780, STD120281157784981940)
Rel_Realization(CRE524446, STD6376579766365465203)
Rel_Realization(CRE571640, STD2370854207656141286)
Rel_Realization(CRE326704, STD1330747404477513456)
Rel_Specialization(CRE010308, CRE176154)
Rel_Specialization(CRE062850, CRE622835)
Rel_Realization(CRE430636, STD6101088217553477368)
Rel_Specialization(CRE447083, CRE082327)
Rel_Realization(CRE124564, STD1729474030500113065)
Rel_Association(CRE170772, CRE333858)
Rel_Association(CRE486813, CRE233748)
Rel_Specialization(CRE854643, CRE356282)
Rel_Specialization(CRE062850, CRE206254)
Rel_Specialization(CRE854643, CRE447083)
Rel_Realization(CRE366835, STD7825391631360540643)
Rel_Realization(CRE036147, STD9002595645551840047)
Rel_Realization(CRE534605, STD7651559068572918361)
Rel_Realization(CRE571640, STD5712315583517003546)
Rel_Realization(CRE344611, STD170604891416369331)
Rel_Realization(CRE080466, STD3740380286179403175)
Rel_Association(CRE486813, CRE308515)
Rel_Realization(CRE076470, STD5308302796388067706)
Rel_Specialization(CRE275483, CRE267468)
Rel_Specialization(CRE161451, CRE366835)
Rel_Specialization(CRE636347, CRE257668)
Rel_Specialization(CRE010308, CRE848711)
Rel_Realization(CRE640364, STD3276289354384575579)
Rel_Specialization(CRE161451, CRE732873)
Rel_Specialization(CRE601182, CRE267031)
Rel_Realization(CRE668364, STD6131681216614805009)
Rel_Realization(CRE267468, STD8336011349632423274)
Rel_Realization(CRE146706, STD1392629772430707721)
Rel_Realization(CRE881321, STD602550366812280187)
Rel_Association(CRE760764, CRE541441)
Rel_Association(CRE170772, CRE062850)
Rel_Association(CRE170772, CRE605735)
Rel_Realization(CRE854643, STD8263336799016017600)
Rel_Association(CRE760764, CRE764765)
Rel_Realization(CRE208805, STD1234886326794137231)
Rel_Realization(CRE681823, STD1100106006064507520)
Rel_Realization(CRE440361, STD603508942396023735)
Rel_Association(CRE155155, CRE326704)
Rel_Realization(CRE405411, STD2211190817577300267)
Rel_Specialization(CRE062850, CRE543428)
Rel_Realization(CRE124564, STD2073339972120571381)
Rel_Specialization(CRE223780, CRE783255)
Rel_Specialization(CRE228551, CRE767701)
Rel_Realization(CRE155155, STD3058518917586496527)
Rel_Realization(CRE170772, STD6900918804406646393)
Rel_Specialization(CRE546564, CRE760764)
Rel_Realization(CRE646227, STD7627260682213681033)
Rel_Specialization(CRE062850, CRE524446)
Rel_Association(CRE486813, CRE615744)
Rel_Specialization(CRE233748, CRE180488)
Rel_Specialization(CRE636347, CRE736237)
Rel_Association(CRE170772, CRE426842)
Rel_Association(CRE760764, CRE048612)
Rel_Specialization(CRE708355, CRE344611)
Rel_Realization(CRE326704, STD3293055429165776372)
Rel_Association(CRE170772, CRE727043)
Rel_Realization(CRE058527, STD1434531569007872414)
Rel_Realization(CRE077781, STD8157000111370185576)
Rel_Realization(CRE664571, STD297601816326472383)
@enduml